NAME        = fsa
VERSION     = 1.15.7
RELEASE     = 2
PKGROOT     = /opt/fsa

SRC_SUBDIR  = fsa

PKG_SUFFIX  = tar.gz
SOURCE_PKG  = $(NAME)-$(VERSION).$(PKG_SUFFIX)
SOURCE_DIR  = $(SOURCE_PKG:%.$(PKG_SUFFIX)=%)

TAR_GZ_PKGS = $(SOURCE_PKG)

RPM.EXTRAS  = AutoReq:No
