NAME           = fsa
VERSION        = 1.15.9
RELEASE        = 0
PKGROOT        = /opt/fsa

SRC_SUBDIR     = fsa

SOURCE_NAME    = fsa
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

TAR_GZ_PKGS    = $(SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No
