NAME       = amos
VERSION    = 3.1.0
RELEASE    = 2
PKGROOT    = /opt/amos

SRC_SUBDIR = amos

PKG_SUFFIX = tgz
SOURCE_PKG = $(NAME)-$(VERSION).$(PKG_SUFFIX)
SOURCE_DIR = $(SOURCE_PKG:%.$(PKG_SUFFIX)=%)

TGZ_PKGS   = $(SOURCE_PKG)

RPM.EXTRAS = AutoReq:No
